### ISSUE TITLE
Checklist of what Recruiting Team needs to Complete 

### ISSUE THREAD

**Issue by beccatran** [bitprj/people#115]
**Objectives**

**Collaborators and Tasks**

- [x] It’s very difficult to see what the interviewer thought about the case/blog prompts because the notes section is not easy to read and is kinda inconsistent
- [x] Instead of a grade (which doesn’t really help me as their manager identify their strengths and weaknesses), I would like the interviewer to upload a markdown file using the interview form that you made with both the grade from 1-4 as well as notes on the response that the interviewee gave
- [x] Since we’re not determining if our applicants are good/bad, it would be better to take the interview time to take thorough notes and make evaluations later
- [x] You can even make it the managers responsibility to grade the responses so that you can ensure they have read your notes and evaluations (talk to me if this doesn’t make sense)
- [x] Need a column for interviewer next to interview date
- [x] The first part in the eduflow should be for the new member to dm the manager they are starting the onboarding process
- [x] The last part of the eduflow should be for the new member to dm the manager and onboarding associate that they are done with onboarding (so we can make sure they are prepared to start working) and set up a 1:1 with the manager
- [x] Merging directory and application Airtable needs to be completed before Town Hall tomorrow
- [x] Instead of “Accepted” we need “Onboarding” and then “Active”, “Hiatus”, “Offboarding”, “Removed”, “Need Confirmation” in that order
- [x] Add question in form to upload picture
- [x] Add demographic questions
- [x] Add question about needing any extra support (for applicants with special needs)
- [x] Everything else in the directory Airtable

**Deadline ASAP**

Please delegate these tasks to your team members!

**Comment by kphillips20** [comment]
still confused on merging so I'm hoping to set up a 1-1
