### ISSUE TITLE
Sourcing Road Map for 4/18-5/2

### ISSUE THREAD

**Issue by ojgao** [bitprj/people#35]
**4/18-4/19:**
@bitprj/people 
- [x] Cement Job Descriptions for sourcing
- [x] Meet with Department Heads to discuss key qualities that they want from applicants as well as solidify interview questions
- [x] Identify key traits for a sourcer
@jazcheng and @
- [x] Work with @bitprj/marketing to determine what they want for interviews 
- [x] Reach out to people for Assistant Director of Content with email template from @jazcheng and becca
@ojgao 
- [x] solidify Sourcing job description
- [ ] create email template for sourcing outreach
- [ ] modify airtable/ application
**By 4/15**
@bitprj/people 
- [ ] Cement interview process and discuss with department heads for any changes
- [ ] Continue to reach out to fill positions for sourcing(10 min signups) and Ass. Dir. of Content
- [ ] reach out to people for Dev Rel positions (need 3 signups)
- [ ] onboard any extraordinary sourcing applicants to help with interviews over the weekend
- [ ] Implement ID system 
**4/18 - 4/25**
@bitprj/people 
- [ ] Start the interview process, interview for department you are working in tandem with
- [ ] Weekly quotas for reaching people
**4/26- 5/2** 
@bitprj/people 
- [ ] Continue to fill in positions that are still required
- [ ] Start reaching out to high schoolers and Diversity applicants. 
- [ ] Weekly souring quotas
